language: node_js
node_js:
  - "node"
before_install:
  - npm i -g npm
branches:
  only:
    - master
script:
  - npm run lint
  - npm test
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'